### ISSUE TITLE
About Box Title to show Sukaku Explainer

### ISSUE THREAD

**Issue by 1to9only** [SudokuMonster/SukakuExplainer#29]
as per title. cosmetic change.

**Comment by 1to9only** [comment]
(https://github.com/SudokuMonster/SukakuExplainer/tree/aboutboxtitlefix) can be pilled/merged anytime before the next release.

**Comment by SudokuMonster** [comment]
@1to9only please add where to do this on wiki page “cosmetic and version changes” which helps whoever to update as release/versions change thanks

**Comment by 1to9only** [comment]
[rant on]It is only a 2-character change. It was hardly worth my time to raise this, if the previous change had been tested![rant off]

What I meant was:
This has been fixed, in the **aboutboxtitlefix** branch, this branch **can be pulled/merged anytime before the next release.**

And for a 2-character fix, I've written more charaters than it's worth living!

**Comment by SudokuMonster** [comment]
@1to9only I agree that these cosmetic changes are not going to impact on the general scheme of things. I started the wiki page specifically to put all these cosmetic changes which I’ve already done (version, about, release) in one place with guide to how to do it so that somebody else can do it for you in bulk when the next version release comes

**Comment by SudokuMonster** [comment]
I updated the wiki page

**Comment by dobrichev** [comment]
After the merge I've done, the changes should be in master. Keeping version an titles on single place is still an open issue.

**Comment by SudokuMonster** [comment]
Just in case it isn’t sorted at some stage. All the change spots are on the wiki page
