### ISSUE TITLE
Changing to New Ratings mode resets Sudoku

### ISSUE THREAD

**Issue by anonymous7002** [SudokuMonster/SukakuExplainer#84]
When I change to new ratings, it clears the the Sudoku grid.
I have to input the Sudoku again.

**Comment by SudokuMonster** [comment]
Hi anonymous7002,

That is done on purpose. Any change in Variants, Rating System or "Bring back SE121" will reset the grid. It is because the progress of the solution has to be in reference to one system which is the 1st line in the Welcome window or the Frame Heading which is in the top left corner

**Comment by 1to9only** [comment]
To not clear the grid on option change, call setGrid, e.g.
`engine.setGrid(sudokuPanel.getSudokuGrid());`
I would trust the user to realise that the grid may become unsolvable.
It would also allow scenario like: generate a regular sudoku, switch to latin square to see if sudoku is solvable as a latin square, then switch back to vanilla sudoku.

**Comment by SudokuMonster** [comment]
Good point 1to9only. Especially with Ratings change & bring back SE121 things can get messy though. I would still for the time being keep the grid clearing with every variant change & some options selection as referencing a problem or solving technique would be easier.

As 1to9only mentioned, you can modify the code personally but that is currently un-supported.

**Comment by anonymous7002** [comment]
Switching to new ratings doesn't change sudoku rules.
Thus it should not reset.

**Comment by SudokuMonster** [comment]
It does change some of the solving technique hierarchy & and some of the technique ratings. So some puzzles may solve in a completely different way and not just acquire a new rating!

```
....7....
.25...8..
8.31.52..
.4..8....
.1953.6.4
......9..
9........
..6..7.3.
2...694..
```
New Rating: ER = 1.6 (naked single)
Old Rating: ER = 2.0 (Direct hidden pair)

Alternating between the systems could muddle the rating and solving.
You can always copy the Pencilmarks between the both systems.
That at least guarantees that the user knows what they are doing rather than
altering the rating by mistake and getting an erroneous un-intended result.

This Board clearing was intended to make it easier and clearer not to make it more 
difficult for the user.
That was my intention at least. I will revise this if needed.
